conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from .views import home_page

app_name = 'home'

urlpatterns = [
    path('', home_page, name='home-page'),
]

products/urls.py
from django.urls import path
from .views import CategoryDetailView, OrderProductView, CategoryListView, ProductDetailView, ProductListView, AddReviewView, UpdateReviewView, DeleteReviewView

app_name = 'products'

urlpatterns = [
    path('product-list/', ProductListView.as_view(), name='product-list'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),  
    path('add-review/<int:pk>/', AddReviewView.as_view(), name='add-review'),
    path('update-review/<int:pk>/', UpdateReviewView.as_view(), name='update-review'),
    path('delete-review/<int:pk>/', DeleteReviewView.as_view(), name='delete-review'),
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('category-detail/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('product/<int:pk>/order/', OrderProductView.as_view(), name='product-order'), 
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit-profile/', ProfileUpdateView.as_view(), name='edit-profile'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mening sahifam{% endblock %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            
        nav {
            background-color: #6f7274;
            padding: 10px 20px;
            display: flex;
            align-items: center;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        nav a:hover {
            text-decoration: underline;
        }
        .container {
            padding: 20px;
            margin: 20px auto;
            background-color: #ffffff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(85, 83, 83, 0.1);
            flex: 1;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            font-weight: bold;
        }
        input[type="text"],
        input[type="password"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        input[type="submit"],
        button {
            background-color: #080808;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
        input[type="submit"]:hover,
        button:hover {
            background-color: #078923;
        }
        .error-message {
            color: red;
            margin-top: 5px;
        }
        .success-message {
            color: green;
            margin-top: 5px;
        }
        footer {
            background-color: #625d5d;
            color: #fff;
            padding: 20px 0;
            text-align: center;
        }
        footer a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        footer a:hover {
            text-decoration: underline;
        }
        footer .social-icons a {
            display: inline-block;
            margin: 0 10px;
        }
        footer .social-icons img {
            width: 24px;
            height: 24px;
        }
        .social-icons{
            margin: 10px;
        }
    </style>
</head>
<body>
    <nav>
        <a href="{% url 'home:home-page' %}">Home</a>
        <a href="{% url 'products:product-list' %}">Products</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'users:profile' %}">Profile</a>
            <a href="{% url 'users:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'users:register' %}">Register</a>
            <a href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <footer>
        <div class="social-icons">
            <a href="https://www.facebook.com" target="_blank">
                <img src="https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg" alt="Facebook">
            </a>
            <a href="https://www.twitter.com" target="_blank">
                <img src="https://upload.wikimedia.org/wikipedia/commons/6/6f/Logo_of_Twitter.svg" alt="Twitter">
            </a>
            <a href="https://www.instagram.com" target="_blank">
                <img src="https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png" alt="Instagram">
            </a>
        </div>
        <div>
            <a href="#footer">Maxfiylik siyosati</a> |
            <a href="#footer">Xizmat ko'rsatish shartlari</a> |
            <a href="#footer">Biz bilan bog'lanish</a>
        </div>
    </footer>
</body>
</html>

templates/index.html
{% extends "base.html" %}

    <title>{% block title %} Bosh Sahifa {% endblock %}</title>

{% block content %}
    <h1>Hush kelibsiz!</h1>
    <p>Bu yerda siz turli xildagi arralarni topishingiz mumkin!</p>
    <a style="text-decoration: wavy; color: rgb(103, 100, 100);" href="{% url 'products:product-list' %}"><button>Uskunalarni Ko'rish</button></a>
{% endblock content %}